image: maven:3.6.0-jdk-8

stages:
  - build

build:
  stage: build
  tags:
    - docker
  script:
    - 'mvn package'
  artifacts:
    paths:
      - '/builds/canabrook/edireader-core/edireader/target/*.jar'


