/*
 * Copyright 2005-2015 by BerryWorks Software, LLC. All rights reserved.
 *
 * This file is part of EDIReader. You may obtain a license for its use directly from
 * BerryWorks Software, and you may also choose to use this software under the terms of the
 * GPL version 3. Other products in the EDIReader software suite are available only by licensing
 * with BerryWorks. Only those files bearing the GPL statement below are available under the GPL.
 *
 * EDIReader is free software: you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 * EDIReader is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with EDIReader.  If not,
 * see <http://www.gnu.org/licenses/>.
 */

/*
*  Generated by plugin generator utility by BerryWorks Software, LLC.
*
*  using /home/mayberry/IntelliJProjects/edireader-trunk/testdata/sef/hipaa/834_X095.SEF
*  on Sat Aug 02 21:26:45 CDT 2008
*/
package com.berryworks.edireader.plugin;

import com.berryworks.edireader.Plugin;

public class ANSI_834 extends Plugin
{
  public ANSI_834()
  {
    super("834", "Benefit Enrollment and Maintenance");
    loops = new LoopDescriptor[]{
      new LoopDescriptor("1100", "ACT", 2, "/1000"),
      new LoopDescriptor("2320", "COB", 3, "/2000/2300"),
      new LoopDescriptor("2200", "DSB", 2, "/2000"),
      new LoopDescriptor("2300", "HD", 2, "/2000"),
      new LoopDescriptor("2000", "INS", 1, ANY_CONTEXT),
      new LoopDescriptor("2310", "LX", 3, "/2000/2300"),
      new LoopDescriptor("1000", "N1", 1, ANY_CONTEXT),
      new LoopDescriptor(CURRENT, "NM1", 3, "/2000/2300/2310"),
      new LoopDescriptor("2100", "NM1", 2, "/2000"),
    };
  }
}
