/*
 *  Generated from 834-4010.SEF
 *  using tools provided by BerryWorks Software, LLC
 */
package com.berryworks.edireader.plugin;

public class ANSI_834_X_005010 extends CompositeAwarePlugin {

    public ANSI_834_X_005010() {
        super("834", "Benefit Enrollment and Maintenance");

        // Loop descriptors generated by EDIReader plugin generator
        loops = new LoopDescriptor[]{
                new LoopDescriptor("1100", "ACT", 2, "/1000/1100"),
                new LoopDescriptor("1100", "ACT", 2, "/1000"),
                new LoopDescriptor(CURRENT, "AMT", 3, "/2000/2100/2300"),
                new LoopDescriptor(CURRENT, "AMT", 2, "/2000/2100"),
                new LoopDescriptor(CURRENT, "BGN", 0, ANY_CONTEXT),
                new LoopDescriptor("2320", "COB", 4, "/2000/2100/2300/2320"),
                new LoopDescriptor("2320", "COB", 4, "/2000/2100/2300"),
                new LoopDescriptor(CURRENT, "DMG", 2, "/2000/2100"),
                new LoopDescriptor("2200", "DSB", 3, "/2000/2100/2200"),
                new LoopDescriptor("2200", "DSB", 3, "/2000/2100"),
                new LoopDescriptor(CURRENT, "DTP", 5, "/2000/2100/2300/2700/2750"),
                new LoopDescriptor(CURRENT, "DTP", 4, "/2000/2100/2300/2320"),
                new LoopDescriptor(CURRENT, "DTP", 3, "/2000/2100/2200"),
                new LoopDescriptor(CURRENT, "DTP", 3, "/2000/2100/2300"),
                new LoopDescriptor(CURRENT, "DTP", 1, "/2000"),
                new LoopDescriptor(CURRENT, "DTP", 0, ANY_CONTEXT),
                new LoopDescriptor(CURRENT, "EC", 2, "/2000/2100"),
                new LoopDescriptor("2300", "HD", 3, "/2000/2100/2300"),
                new LoopDescriptor("2300", "HD", 3, "/2000/2100"),
                new LoopDescriptor(CURRENT, "HLH", 2, "/2000/2100"),
                new LoopDescriptor(CURRENT, "ICM", 2, "/2000/2100"),
                new LoopDescriptor(CURRENT, "IDC", 3, "/2000/2100/2300"),
                new LoopDescriptor("2000", "INS", 1, ANY_CONTEXT),
                new LoopDescriptor(CURRENT, "LE", 3, "/2000/2100/2300"),
                new LoopDescriptor(CURRENT, "LS", 3, "/2000/2100/2300"),
                new LoopDescriptor(CURRENT, "LUI", 2, "/2000/2100"),
                new LoopDescriptor("2310", "LX", 4, "/2000/2100/2300/2310"),
                new LoopDescriptor("2700", "LX", 4, "/2000/2100/2300/2700"),
                new LoopDescriptor("2310", "LX", 4, "/2000/2100/2300"),
                new LoopDescriptor("2700", "LX", 4, "/2000/2100/2300"),
                new LoopDescriptor("2750", "N1", 5, "/2000/2100/2300/2700/2750"),
                new LoopDescriptor("2750", "N1", 5, "/2000/2100/2300/2700"),
                new LoopDescriptor("1000", "N1", 1, ANY_CONTEXT),
                new LoopDescriptor(CURRENT, "N3", 5, "/2000/2100/2300/2320/2330"),
                new LoopDescriptor(CURRENT, "N3", 4, "/2000/2100/2300/2310"),
                new LoopDescriptor(CURRENT, "N3", 2, "/2000/2100"),
                new LoopDescriptor(CURRENT, "N4", 5, "/2000/2100/2300/2320/2330"),
                new LoopDescriptor(CURRENT, "N4", 4, "/2000/2100/2300/2310"),
                new LoopDescriptor(CURRENT, "N4", 2, "/2000/2100"),
                new LoopDescriptor("2330", "NM1", 5, "/2000/2100/2300/2320/2330"),
                new LoopDescriptor(CURRENT, "NM1", 4, "/2000/2100/2300/2310"),
                new LoopDescriptor("2330", "NM1", 5, "/2000/2100/2300/2320"),
                new LoopDescriptor("2100", "NM1", 2, "/2000/2100"),
                new LoopDescriptor("2100", "NM1", 2, "/2000"),
                new LoopDescriptor(CURRENT, "PER", 5, "/2000/2100/2300/2320/2330"),
                new LoopDescriptor(CURRENT, "PER", 4, "/2000/2100/2300/2310"),
                new LoopDescriptor(CURRENT, "PER", 2, "/2000/2100"),
                new LoopDescriptor(CURRENT, "PLA", 4, "/2000/2100/2300/2310"),
                new LoopDescriptor(CURRENT, "QTY", 0, ANY_CONTEXT),
                new LoopDescriptor(CURRENT, "REF", 5, "/2000/2100/2300/2700/2750"),
                new LoopDescriptor(CURRENT, "REF", 4, "/2000/2100/2300/2320"),
                new LoopDescriptor(CURRENT, "REF", 3, "/2000/2100/2300"),
                new LoopDescriptor(CURRENT, "REF", 1, "/2000"),
                new LoopDescriptor(CURRENT, "REF", 0, ANY_CONTEXT),
                new LoopDescriptor(CURRENT, "ST", 0, ANY_CONTEXT),
        };

        composites.put("QTY-3", "");
        composites.put("REF-4", "");
        composites.put("INS-6", "");
        composites.put("DMG-5", "");
        composites.put("PRV-5", "");
        composites.put("K3-3", "");
        composites.put("HI-1", "");
        composites.put("HI-2", "");
        composites.put("HI-3", "");
        composites.put("HI-4", "");
        composites.put("HI-5", "");
        composites.put("HI-6", "");
        composites.put("HI-7", "");
        composites.put("HI-8", "");
        composites.put("HI-9", "");
        composites.put("HI-10", "");
        composites.put("HI-11", "");
        composites.put("HI-12", "");
    }
}  
