package com.berryworks.edireader.plugin;/*
 *  Generated from 41F997_A.SEF
 *  using tools provided by BerryWorks Software, LLC
 */

public class ANSI_997_X_004010 extends CompositeAwarePlugin {

    public ANSI_997_X_004010() {
        super("997", "Functional Acknowledgment");

        // Loop descriptors generated by EDIReader plugin generator
        loops = new LoopDescriptor[]{
                new LoopDescriptor(CURRENT, "AK1", 0, ANY_CONTEXT),
                new LoopDescriptor("AK2", "AK2", 1, ANY_CONTEXT),
                new LoopDescriptor("AK3", "AK3", 2, "/AK2/AK3"),
                new LoopDescriptor("AK3", "AK3", 2, "/AK2"),
                new LoopDescriptor(CURRENT, "AK4", 2, "/AK2/AK3"),
                new LoopDescriptor(CURRENT, "AK5", 1, "/AK2"),
                new LoopDescriptor(CURRENT, "AK9", 0, ANY_CONTEXT),
                new LoopDescriptor(CURRENT, "SE", 0, ANY_CONTEXT),
                new LoopDescriptor(CURRENT, "ST", 0, ANY_CONTEXT),
        };

        composites.put("AK4-1", "");

    }
}  
